# 医疗影像诊断系统 Pre-commit 配置
# 在提交代码前自动运行代码质量检查和格式化

repos:
  # Python 代码格式化和检查
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
        files: ^backend/.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: ^backend/.*\.py$

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        files: ^backend/.*\.py$
        additional_dependencies: [flake8-docstrings]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        files: ^backend/.*\.py$
        additional_dependencies: [types-all]

  # JavaScript/TypeScript 格式化和检查
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|md|yml|yaml)$
        exclude: ^backend/

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.50.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        exclude: ^backend/
        additional_dependencies:
          - eslint@8.50.0
          - "@typescript-eslint/eslint-plugin@6.7.0"
          - "@typescript-eslint/parser@6.7.0"

  # 通用检查
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: \.md$
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-added-large-files
        args: ['--maxkb=10240']  # 10MB
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  # SQL 格式化
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.2
    hooks:
      - id: sqlfluff-lint
        files: \.sql$
        additional_dependencies: ['sqlfluff-templater-dbt']
      - id: sqlfluff-fix
        files: \.sql$
        additional_dependencies: ['sqlfluff-templater-dbt']

  # Docker 文件检查
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        files: Dockerfile.*

  # 安全检查
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json

# 配置选项
default_language_version:
  python: python3.9
  node: 18.17.0

# 排除文件
exclude: |
  (?x)^(
    .*\.min\.(js|css)|
    .*\.bundle\.(js|css)|
    node_modules/.*|
    \.next/.*|
    dist/.*|
    build/.*|
    __pycache__/.*|
    \.venv/.*|
    venv/.*|
    \.git/.*
  )$
