"""server schema baseline

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-05-08 00:00:00
"""

from __future__ import annotations

from alembic import op

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


SCHEMA_STATEMENTS = [
    '/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */',
    '/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */',
    '/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */',
    '/*!50503 SET NAMES utf8mb4 */',
    '/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */',
    "/*!40103 SET TIME_ZONE='+00:00' */",
    '/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */',
    '/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */',
    "/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */",
    '/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */',
    'DROP TABLE IF EXISTS `ai_tasks`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `ai_tasks` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `task_id` varchar(64) NOT NULL,\n  `study_id` int NOT NULL,\n  `task_name` varchar(100) NOT NULL,\n  `task_type` varchar(50) NOT NULL,\n  `model_name` varchar(100) NOT NULL,\n  `model_version` varchar(20) DEFAULT NULL,\n  `input_parameters` json DEFAULT NULL,\n  `status` enum('PENDING','RUNNING','COMPLETED','FAILED','CANCELLED') NOT NULL,\n  `progress` float DEFAULT NULL,\n  `started_at` datetime DEFAULT NULL,\n  `completed_at` datetime DEFAULT NULL,\n  `duration` float DEFAULT NULL,\n  `result` json DEFAULT NULL,\n  `confidence` float DEFAULT NULL,\n  `error_message` text,\n  `notes` text,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `created_by` int DEFAULT NULL,\n  `updated_by` int DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  `deleted_at` datetime DEFAULT NULL,\n  `deleted_by` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `task_id` (`task_id`),\n  KEY `study_id` (`study_id`),\n  CONSTRAINT `ai_tasks_ibfk_1` FOREIGN KEY (`study_id`) REFERENCES `studies` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `departments`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    'CREATE TABLE `departments` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `code` varchar(50) NOT NULL,\n  `name` varchar(100) NOT NULL,\n  `full_name` varchar(200) DEFAULT NULL,\n  `description` text,\n  `parent_id` int DEFAULT NULL,\n  `level` int DEFAULT NULL,\n  `path` varchar(500) DEFAULT NULL,\n  `sort_order` int DEFAULT NULL,\n  `status` varchar(20) NOT NULL,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `code` (`code`),\n  KEY `parent_id` (`parent_id`),\n  CONSTRAINT `departments_ibfk_1` FOREIGN KEY (`parent_id`) REFERENCES `departments` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `diagnostic_reports`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `diagnostic_reports` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `report_number` varchar(50) NOT NULL,\n  `study_id` int NOT NULL,\n  `patient_id` int NOT NULL,\n  `template_id` int DEFAULT NULL,\n  `report_type` enum('RADIOLOGY','PATHOLOGY','LABORATORY','ULTRASOUND','ENDOSCOPY','ECG','OTHER') NOT NULL,\n  `report_title` varchar(200) NOT NULL,\n  `status` enum('DRAFT','IN_REVIEW','APPROVED','FINALIZED','CANCELLED','ARCHIVED') NOT NULL,\n  `priority` enum('LOW','NORMAL','HIGH','URGENT','STAT') DEFAULT NULL,\n  `clinical_history` text,\n  `examination_technique` text,\n  `findings` text NOT NULL,\n  `impression` text NOT NULL,\n  `recommendations` text,\n  `structured_data` json DEFAULT NULL,\n  `measurements` json DEFAULT NULL,\n  `annotations` json DEFAULT NULL,\n  `primary_diagnosis` varchar(200) DEFAULT NULL,\n  `secondary_diagnosis` text,\n  `diagnosis_codes` json DEFAULT NULL,\n  `diagnosis_level` enum('NORMAL','ABNORMAL','SUSPICIOUS','MALIGNANT','BENIGN','INDETERMINATE') DEFAULT NULL,\n  `confidence_score` float DEFAULT NULL,\n  `examination_date` date DEFAULT NULL,\n  `report_date` date NOT NULL,\n  `reviewed_date` date DEFAULT NULL,\n  `finalized_date` date DEFAULT NULL,\n  `reporting_physician` varchar(100) NOT NULL,\n  `reviewing_physician` varchar(100) DEFAULT NULL,\n  `attending_physician` varchar(100) DEFAULT NULL,\n  `ai_assisted` tinyint(1) DEFAULT NULL,\n  `ai_suggestions` json DEFAULT NULL,\n  `ai_confidence` float DEFAULT NULL,\n  `quality_score` float DEFAULT NULL,\n  `quality_notes` text,\n  `urgency_flag` tinyint(1) DEFAULT NULL,\n  `critical_flag` tinyint(1) DEFAULT NULL,\n  `follow_up_required` tinyint(1) DEFAULT NULL,\n  `follow_up_date` date DEFAULT NULL,\n  `notes` text,\n  `tags` json DEFAULT NULL,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `created_by` int DEFAULT NULL,\n  `updated_by` int DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  `deleted_at` datetime DEFAULT NULL,\n  `deleted_by` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `report_number` (`report_number`),\n  KEY `template_id` (`template_id`),\n  CONSTRAINT `diagnostic_reports_ibfk_1` FOREIGN KEY (`template_id`) REFERENCES `report_templates` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `image_annotations`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `image_annotations` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `image_file_id` int NOT NULL COMMENT 'å½±åƒ\x8fæ–‡ä»¶ID',\n  `annotation_type` enum('POINT','LINE','RECTANGLE','CIRCLE','POLYGON','FREEHAND','TEXT','MEASUREMENT') NOT NULL,\n  `coordinates` json NOT NULL,\n  `label` varchar(100) DEFAULT NULL,\n  `description` text,\n  `measurement_value` float DEFAULT NULL,\n  `measurement_unit` varchar(20) DEFAULT NULL,\n  `color` varchar(7) DEFAULT NULL,\n  `thickness` int DEFAULT NULL,\n  `opacity` float DEFAULT NULL,\n  `is_visible` tinyint(1) DEFAULT NULL,\n  `is_locked` tinyint(1) DEFAULT NULL,\n  `notes` text,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `created_by` int DEFAULT NULL,\n  `updated_by` int DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  `deleted_at` datetime DEFAULT NULL,\n  `deleted_by` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  KEY `idx_image_file_id` (`image_file_id`),\n  CONSTRAINT `fk_image_annotations_image_file` FOREIGN KEY (`image_file_id`) REFERENCES `image_files` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=3285 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `image_files`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `image_files` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `file_uuid` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'æ–‡ä»¶å”¯ä¸€æ\xa0‡è¯†',\n  `original_filename` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'åŽŸå§‹æ–‡ä»¶å\x90\x8d',\n  `file_type` enum('DICOM','JPEG','PNG','TIFF','OTHER') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'OTHER',\n  `mime_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'MIMEç±»åž‹',\n  `file_size` bigint NOT NULL DEFAULT '0' COMMENT 'æ–‡ä»¶å¤§å°\x8f(å\xad—èŠ‚)',\n  `file_hash` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'æ–‡ä»¶MD5å“ˆå¸Œå€¼',\n  `storage_path` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'å\xad˜å‚¨è·¯å¾„',\n  `thumbnail_path` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'ç¼©ç•¥å›¾è·¯å¾„',\n  `uploaded_by` int NOT NULL COMMENT 'ä¸Šä¼\xa0ç”¨æˆ·ID',\n  `patient_id` int DEFAULT NULL COMMENT 'å…³è\x81”æ‚£è€…ID',\n  `study_id` int DEFAULT NULL COMMENT 'å…³è\x81”æ£€æŸ¥ID',\n  `series_id` int DEFAULT NULL COMMENT 'å…³è\x81”åº\x8fåˆ—ID',\n  `modality` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'å½±åƒ\x8fæ¨¡æ€\x81(CT/MRI/X-Rayç\xad‰)',\n  `body_part` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'æ£€æŸ¥éƒ¨ä½\x8d',\n  `study_date` datetime DEFAULT NULL COMMENT 'æ£€æŸ¥æ—¥æœŸ',\n  `description` text COLLATE utf8mb4_unicode_ci COMMENT 'æ–‡ä»¶æ\x8f\x8fè¿°',\n  `annotation` text COLLATE utf8mb4_unicode_ci COMMENT '标注数据(JSON格式)',\n  `status` enum('UPLOADING','UPLOADED','PROCESSING','PROCESSED','FAILED','ARCHIVED','DELETED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'UPLOADING',\n  `upload_progress` int NOT NULL DEFAULT '0' COMMENT 'ä¸Šä¼\xa0è¿›åº¦(0-100)',\n  `is_chunked` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'æ˜¯å\x90¦åˆ†ç‰‡ä¸Šä¼\xa0',\n  `total_chunks` int DEFAULT NULL COMMENT 'æ€»åˆ†ç‰‡æ•°',\n  `uploaded_chunks` text COLLATE utf8mb4_unicode_ci COMMENT 'å·²ä¸Šä¼\xa0åˆ†ç‰‡åˆ—è¡¨(JSON)',\n  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'æ˜¯å\x90¦å·²åˆ\xa0é™¤',\n  `deleted_at` datetime DEFAULT NULL COMMENT 'åˆ\xa0é™¤æ—¶é—´',\n  `deleted_by` int DEFAULT NULL COMMENT 'åˆ\xa0é™¤ç”¨æˆ·ID',\n  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'åˆ›å»ºæ—¶é—´',\n  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'æ›´æ–°æ—¶é—´',\n  `uploaded_at` datetime DEFAULT NULL COMMENT 'ä¸Šä¼\xa0å®Œæˆ\x90æ—¶é—´',\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `file_uuid` (`file_uuid`),\n  KEY `idx_file_uuid` (`file_uuid`),\n  KEY `idx_uploaded_by` (`uploaded_by`),\n  KEY `idx_patient_id` (`patient_id`),\n  KEY `idx_study_id` (`study_id`),\n  KEY `idx_modality` (`modality`),\n  KEY `idx_created_at` (`created_at`),\n  KEY `idx_status` (`status`),\n  KEY `idx_is_deleted` (`is_deleted`),\n  KEY `idx_series_id` (`series_id`),\n  CONSTRAINT `image_files_ibfk_1` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT,\n  CONSTRAINT `image_files_ibfk_2` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`) ON DELETE SET NULL,\n  CONSTRAINT `image_files_ibfk_3` FOREIGN KEY (`series_id`) REFERENCES `series` (`id`) ON DELETE SET NULL\n) ENGINE=InnoDB AUTO_INCREMENT=167 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='å½±åƒ\x8fæ–‡ä»¶è¡¨'",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `instances`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `instances` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `sop_instance_uid` varchar(64) NOT NULL,\n  `sop_class_uid` varchar(64) DEFAULT NULL,\n  `instance_number` int DEFAULT NULL,\n  `series_id` int NOT NULL,\n  `file_path` varchar(500) DEFAULT NULL,\n  `file_name` varchar(255) DEFAULT NULL,\n  `file_size` int DEFAULT NULL,\n  `file_hash` varchar(64) DEFAULT NULL,\n  `image_type` varchar(64) DEFAULT NULL,\n  `rows` int DEFAULT NULL,\n  `columns` int DEFAULT NULL,\n  `bits_allocated` int DEFAULT NULL,\n  `bits_stored` int DEFAULT NULL,\n  `slice_location` float DEFAULT NULL,\n  `image_position` varchar(64) DEFAULT NULL,\n  `window_center` float DEFAULT NULL,\n  `window_width` float DEFAULT NULL,\n  `status` enum('UPLOADING','UPLOADED','PROCESSING','PROCESSED','FAILED','ARCHIVED') NOT NULL,\n  `quality` enum('EXCELLENT','GOOD','ACCEPTABLE','POOR','UNACCEPTABLE') DEFAULT NULL,\n  `thumbnail_path` varchar(500) DEFAULT NULL,\n  `preview_path` varchar(500) DEFAULT NULL,\n  `processed_at` datetime DEFAULT NULL,\n  `notes` text,\n  `dicom_metadata` json DEFAULT NULL,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `created_by` int DEFAULT NULL,\n  `updated_by` int DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  `deleted_at` datetime DEFAULT NULL,\n  `deleted_by` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `sop_instance_uid` (`sop_instance_uid`),\n  KEY `series_id` (`series_id`),\n  CONSTRAINT `instances_ibfk_1` FOREIGN KEY (`series_id`) REFERENCES `series` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `notifications`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `notifications` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `notification_type` enum('INFO','WARNING','ERROR','SUCCESS','SYSTEM','REMINDER') NOT NULL,\n  `title` varchar(200) NOT NULL,\n  `content` text NOT NULL,\n  `status` enum('PENDING','SENT','READ','FAILED','EXPIRED') DEFAULT NULL,\n  `recipient_id` int DEFAULT NULL,\n  `recipient_type` varchar(50) DEFAULT NULL,\n  `recipient_email` varchar(200) DEFAULT NULL,\n  `recipient_phone` varchar(20) DEFAULT NULL,\n  `sender_id` int DEFAULT NULL,\n  `sender_name` varchar(100) DEFAULT NULL,\n  `channels` json DEFAULT NULL,\n  `related_type` varchar(50) DEFAULT NULL,\n  `related_id` varchar(100) DEFAULT NULL,\n  `related_data` json DEFAULT NULL,\n  `scheduled_at` datetime DEFAULT NULL,\n  `sent_at` datetime DEFAULT NULL,\n  `read_at` datetime DEFAULT NULL,\n  `expires_at` datetime DEFAULT NULL,\n  `retry_count` int DEFAULT NULL,\n  `max_retries` int DEFAULT NULL,\n  `last_error` text,\n  `priority` int DEFAULT NULL,\n  `tags` json DEFAULT NULL,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `created_by` int DEFAULT NULL,\n  `updated_by` int DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  `deleted_at` datetime DEFAULT NULL,\n  `deleted_by` int DEFAULT NULL,\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `patient_allergies`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `patient_allergies` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `patient_id` int NOT NULL,\n  `allergen` varchar(200) NOT NULL,\n  `allergen_type` varchar(50) DEFAULT NULL,\n  `reaction` text,\n  `severity` enum('MILD','MODERATE','SEVERE','CRITICAL','UNKNOWN') DEFAULT NULL,\n  `onset_date` date DEFAULT NULL,\n  `last_reaction_date` date DEFAULT NULL,\n  `is_active` tinyint(1) DEFAULT NULL,\n  `verified` tinyint(1) DEFAULT NULL,\n  `notes` text,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `created_by` int DEFAULT NULL,\n  `updated_by` int DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  `deleted_at` datetime DEFAULT NULL,\n  `deleted_by` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  KEY `patient_id` (`patient_id`),\n  CONSTRAINT `patient_allergies_ibfk_1` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `patient_medical_history`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `patient_medical_history` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `patient_id` int NOT NULL,\n  `condition` varchar(200) NOT NULL,\n  `condition_code` varchar(20) DEFAULT NULL,\n  `category` varchar(50) DEFAULT NULL,\n  `onset_date` date DEFAULT NULL,\n  `resolution_date` date DEFAULT NULL,\n  `description` text,\n  `treatment` text,\n  `outcome` varchar(100) DEFAULT NULL,\n  `is_chronic` tinyint(1) DEFAULT NULL,\n  `is_hereditary` tinyint(1) DEFAULT NULL,\n  `severity` enum('MILD','MODERATE','SEVERE','CRITICAL','UNKNOWN') DEFAULT NULL,\n  `related_family_member` varchar(50) DEFAULT NULL,\n  `notes` text,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `created_by` int DEFAULT NULL,\n  `updated_by` int DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  `deleted_at` datetime DEFAULT NULL,\n  `deleted_by` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  KEY `patient_id` (`patient_id`),\n  CONSTRAINT `patient_medical_history_ibfk_1` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `patient_visits`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `patient_visits` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `visit_number` varchar(50) NOT NULL,\n  `patient_id` int NOT NULL,\n  `visit_type` enum('OUTPATIENT','INPATIENT','EMERGENCY','PHYSICAL_EXAM','FOLLOW_UP') NOT NULL,\n  `visit_date` datetime NOT NULL,\n  `department_id` int DEFAULT NULL,\n  `doctor_id` int DEFAULT NULL,\n  `status` enum('SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED','NO_SHOW') NOT NULL,\n  `priority` varchar(20) DEFAULT NULL,\n  `chief_complaint` text,\n  `present_illness` text,\n  `diagnosis_preliminary` text,\n  `diagnosis_final` text,\n  `treatment_plan` text,\n  `temperature` decimal(4,1) DEFAULT NULL,\n  `blood_pressure_systolic` int DEFAULT NULL,\n  `blood_pressure_diastolic` int DEFAULT NULL,\n  `heart_rate` int DEFAULT NULL,\n  `respiratory_rate` int DEFAULT NULL,\n  `oxygen_saturation` decimal(5,2) DEFAULT NULL,\n  `total_cost` decimal(10,2) DEFAULT NULL,\n  `insurance_coverage` decimal(10,2) DEFAULT NULL,\n  `self_payment` decimal(10,2) DEFAULT NULL,\n  `notes` text,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `created_by` int DEFAULT NULL,\n  `updated_by` int DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  `deleted_at` datetime DEFAULT NULL,\n  `deleted_by` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `visit_number` (`visit_number`),\n  KEY `patient_id` (`patient_id`),\n  CONSTRAINT `patient_visits_ibfk_1` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `patients`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `patients` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `patient_id` varchar(50) NOT NULL,\n  `hospital_id` varchar(50) DEFAULT NULL,\n  `name` varchar(100) NOT NULL,\n  `name_en` varchar(200) DEFAULT NULL,\n  `gender` enum('MALE','FEMALE','OTHER','UNKNOWN') NOT NULL,\n  `birth_date` date DEFAULT NULL,\n  `age` int DEFAULT NULL,\n  `id_card` varchar(18) DEFAULT NULL,\n  `passport` varchar(50) DEFAULT NULL,\n  `nationality` varchar(50) DEFAULT NULL,\n  `ethnicity` varchar(50) DEFAULT NULL,\n  `phone` varchar(20) DEFAULT NULL,\n  `phone_backup` varchar(20) DEFAULT NULL,\n  `email` varchar(100) DEFAULT NULL,\n  `address` varchar(500) DEFAULT NULL,\n  `postal_code` varchar(10) DEFAULT NULL,\n  `emergency_contact_name` varchar(100) DEFAULT NULL,\n  `emergency_contact_phone` varchar(20) DEFAULT NULL,\n  `emergency_contact_relation` varchar(50) DEFAULT NULL,\n  `blood_type` enum('A','B','AB','O','UNKNOWN') DEFAULT NULL,\n  `rh_factor` enum('POSITIVE','NEGATIVE','UNKNOWN') DEFAULT NULL,\n  `height` decimal(5,2) DEFAULT NULL,\n  `weight` decimal(5,2) DEFAULT NULL,\n  `bmi` decimal(5,2) DEFAULT NULL,\n  `marital_status` enum('SINGLE','MARRIED','DIVORCED','WIDOWED','UNKNOWN') DEFAULT NULL,\n  `occupation` varchar(100) DEFAULT NULL,\n  `education` varchar(50) DEFAULT NULL,\n  `insurance_type` varchar(50) DEFAULT NULL,\n  `insurance_number` varchar(50) DEFAULT NULL,\n  `status` enum('ACTIVE','INACTIVE','DECEASED','MERGED') NOT NULL,\n  `is_vip` tinyint(1) DEFAULT NULL,\n  `is_high_risk` tinyint(1) DEFAULT NULL,\n  `notes` text,\n  `tags` json DEFAULT NULL,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `created_by` int DEFAULT NULL,\n  `updated_by` int DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  `deleted_at` datetime DEFAULT NULL,\n  `deleted_by` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `patient_id` (`patient_id`),\n  UNIQUE KEY `hospital_id` (`hospital_id`),\n  UNIQUE KEY `id_card` (`id_card`),\n  UNIQUE KEY `passport` (`passport`)\n) ENGINE=InnoDB AUTO_INCREMENT=45 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `permissions`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    'CREATE TABLE `permissions` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `code` varchar(100) NOT NULL,\n  `name` varchar(50) NOT NULL,\n  `description` text,\n  `module` varchar(50) NOT NULL,\n  `resource` varchar(50) NOT NULL,\n  `action` varchar(50) NOT NULL,\n  `status` varchar(20) NOT NULL,\n  `is_system` tinyint(1) DEFAULT NULL,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `code` (`code`)\n) ENGINE=InnoDB AUTO_INCREMENT=30 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `report_findings`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    'CREATE TABLE `report_findings` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `report_id` int NOT NULL,\n  `finding_category` varchar(100) NOT NULL,\n  `finding_description` text NOT NULL,\n  `location` varchar(100) DEFAULT NULL,\n  `severity` varchar(50) DEFAULT NULL,\n  `measurements` json DEFAULT NULL,\n  `coordinates` json DEFAULT NULL,\n  `significance` varchar(100) DEFAULT NULL,\n  `differential_diagnosis` text,\n  `sort_order` int DEFAULT NULL,\n  `is_key_finding` tinyint(1) DEFAULT NULL,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `created_by` int DEFAULT NULL,\n  `updated_by` int DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  `deleted_at` datetime DEFAULT NULL,\n  `deleted_by` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  KEY `report_id` (`report_id`),\n  CONSTRAINT `report_findings_ibfk_1` FOREIGN KEY (`report_id`) REFERENCES `diagnostic_reports` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `report_revisions`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    'CREATE TABLE `report_revisions` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `report_id` int NOT NULL,\n  `revision_number` int NOT NULL,\n  `revision_reason` varchar(200) NOT NULL,\n  `revision_description` text,\n  `previous_content` json NOT NULL,\n  `current_content` json NOT NULL,\n  `changed_fields` json DEFAULT NULL,\n  `revised_by` int NOT NULL,\n  `revised_at` datetime DEFAULT NULL,\n  `approved_by` int DEFAULT NULL,\n  `approved_at` datetime DEFAULT NULL,\n  `created_at` datetime DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  `deleted_at` datetime DEFAULT NULL,\n  `deleted_by` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  KEY `report_id` (`report_id`),\n  CONSTRAINT `report_revisions_ibfk_1` FOREIGN KEY (`report_id`) REFERENCES `diagnostic_reports` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `report_templates`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `report_templates` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `template_name` varchar(100) NOT NULL,\n  `template_code` varchar(50) NOT NULL,\n  `template_type` enum('STRUCTURED','FREE_TEXT','HYBRID','CHECKLIST') NOT NULL,\n  `report_type` enum('RADIOLOGY','PATHOLOGY','LABORATORY','ULTRASOUND','ENDOSCOPY','ECG','OTHER') NOT NULL,\n  `modality` varchar(20) DEFAULT NULL,\n  `body_part` varchar(50) DEFAULT NULL,\n  `template_content` json NOT NULL,\n  `default_values` json DEFAULT NULL,\n  `validation_rules` json DEFAULT NULL,\n  `is_active` tinyint(1) DEFAULT NULL,\n  `is_default` tinyint(1) DEFAULT NULL,\n  `version` varchar(20) DEFAULT NULL,\n  `description` text,\n  `usage_count` int DEFAULT NULL,\n  `last_used_at` datetime DEFAULT NULL,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `created_by` int DEFAULT NULL,\n  `updated_by` int DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  `deleted_at` datetime DEFAULT NULL,\n  `deleted_by` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `template_code` (`template_code`)\n) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `role_permissions`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    'CREATE TABLE `role_permissions` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `role_id` int NOT NULL,\n  `permission_id` int NOT NULL,\n  `granted_at` datetime DEFAULT NULL,\n  `is_active` tinyint(1) DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_role_permission` (`role_id`,`permission_id`),\n  KEY `permission_id` (`permission_id`),\n  CONSTRAINT `role_permissions_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `role_permissions_ibfk_2` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `roles`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    'CREATE TABLE `roles` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `code` varchar(50) NOT NULL,\n  `name` varchar(50) NOT NULL,\n  `description` text,\n  `level` int DEFAULT NULL,\n  `status` varchar(20) NOT NULL,\n  `is_system` tinyint(1) DEFAULT NULL,\n  `is_default` tinyint(1) DEFAULT NULL,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `code` (`code`)\n) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `series`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `series` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `series_instance_uid` varchar(64) NOT NULL,\n  `series_number` int DEFAULT NULL,\n  `study_id` int NOT NULL,\n  `series_date` date DEFAULT NULL,\n  `series_time` varchar(16) DEFAULT NULL,\n  `series_description` varchar(64) DEFAULT NULL,\n  `protocol_name` varchar(64) DEFAULT NULL,\n  `modality` enum('CT','MR','XR','US','NM','PT','MG','DX','CR','DR','RF','SC','OTHER') DEFAULT NULL,\n  `body_part` enum('HEAD','NECK','CHEST','ABDOMEN','PELVIS','SPINE','EXTREMITY','WHOLE_BODY','OTHER') DEFAULT NULL,\n  `slice_thickness` float DEFAULT NULL,\n  `pixel_spacing` varchar(32) DEFAULT NULL,\n  `image_orientation` varchar(64) DEFAULT NULL,\n  `kvp` float DEFAULT NULL,\n  `exposure_time` float DEFAULT NULL,\n  `tube_current` float DEFAULT NULL,\n  `instance_count` int DEFAULT NULL,\n  `total_size` int DEFAULT NULL,\n  `status` enum('RECEIVING','RECEIVED','PROCESSING','PROCESSED','FAILED') NOT NULL,\n  `quality` enum('EXCELLENT','GOOD','ACCEPTABLE','POOR','UNACCEPTABLE') DEFAULT NULL,\n  `notes` text,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `created_by` int DEFAULT NULL,\n  `updated_by` int DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  `deleted_at` datetime DEFAULT NULL,\n  `deleted_by` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `series_instance_uid` (`series_instance_uid`),\n  KEY `study_id` (`study_id`),\n  CONSTRAINT `series_ibfk_1` FOREIGN KEY (`study_id`) REFERENCES `studies` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `studies`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `studies` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `study_instance_uid` varchar(64) NOT NULL,\n  `study_id` varchar(16) DEFAULT NULL,\n  `accession_number` varchar(16) DEFAULT NULL,\n  `patient_id` int NOT NULL,\n  `study_date` date DEFAULT NULL,\n  `study_time` varchar(16) DEFAULT NULL,\n  `study_description` varchar(64) DEFAULT NULL,\n  `modality` enum('CT','MR','XR','US','NM','PT','MG','DX','CR','DR','RF','SC','OTHER') DEFAULT NULL,\n  `body_part` enum('HEAD','NECK','CHEST','ABDOMEN','PELVIS','SPINE','EXTREMITY','WHOLE_BODY','OTHER') DEFAULT NULL,\n  `referring_physician` varchar(64) DEFAULT NULL,\n  `performing_physician` varchar(64) DEFAULT NULL,\n  `reading_physician` varchar(64) DEFAULT NULL,\n  `institution_name` varchar(64) DEFAULT NULL,\n  `station_name` varchar(16) DEFAULT NULL,\n  `manufacturer` varchar(64) DEFAULT NULL,\n  `model_name` varchar(64) DEFAULT NULL,\n  `series_count` int DEFAULT NULL,\n  `instance_count` int DEFAULT NULL,\n  `total_size` int DEFAULT NULL,\n  `status` enum('SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED','ARCHIVED') NOT NULL,\n  `priority` varchar(20) DEFAULT NULL,\n  `quality` enum('EXCELLENT','GOOD','ACCEPTABLE','POOR','UNACCEPTABLE') DEFAULT NULL,\n  `notes` text,\n  `tags` json DEFAULT NULL,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `created_by` int DEFAULT NULL,\n  `updated_by` int DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  `deleted_at` datetime DEFAULT NULL,\n  `deleted_by` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `study_instance_uid` (`study_instance_uid`)\n) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `system_alerts`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `system_alerts` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `alert_type` varchar(50) NOT NULL,\n  `alert_level` enum('DEBUG','INFO','WARNING','ERROR','CRITICAL') NOT NULL,\n  `alert_title` varchar(200) NOT NULL,\n  `alert_message` text NOT NULL,\n  `source_type` varchar(50) DEFAULT NULL,\n  `source_id` varchar(100) DEFAULT NULL,\n  `server_name` varchar(100) DEFAULT NULL,\n  `is_resolved` tinyint(1) DEFAULT NULL,\n  `resolved_at` datetime DEFAULT NULL,\n  `resolved_by` int DEFAULT NULL,\n  `resolution_notes` text,\n  `alert_data` json DEFAULT NULL,\n  `threshold_value` float DEFAULT NULL,\n  `current_value` float DEFAULT NULL,\n  `notification_sent` tinyint(1) DEFAULT NULL,\n  `notification_count` int DEFAULT NULL,\n  `last_notification_at` datetime DEFAULT NULL,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `created_by` int DEFAULT NULL,\n  `updated_by` int DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  `deleted_at` datetime DEFAULT NULL,\n  `deleted_by` int DEFAULT NULL,\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `system_configs`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `system_configs` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `config_key` varchar(100) NOT NULL,\n  `config_name` varchar(200) NOT NULL,\n  `config_type` enum('SYSTEM','DATABASE','SECURITY','NOTIFICATION','AI','DICOM','STORAGE','NETWORK','UI','WORKFLOW') NOT NULL,\n  `data_type` enum('STRING','INTEGER','FLOAT','BOOLEAN','JSON','ARRAY','DATE','DATETIME') NOT NULL,\n  `config_value` text,\n  `default_value` text,\n  `description` text,\n  `is_required` tinyint(1) DEFAULT NULL,\n  `is_encrypted` tinyint(1) DEFAULT NULL,\n  `is_readonly` tinyint(1) DEFAULT NULL,\n  `is_system` tinyint(1) DEFAULT NULL,\n  `validation_rules` json DEFAULT NULL,\n  `allowed_values` json DEFAULT NULL,\n  `min_value` float DEFAULT NULL,\n  `max_value` float DEFAULT NULL,\n  `config_group` varchar(100) DEFAULT NULL,\n  `sort_order` int DEFAULT NULL,\n  `is_active` tinyint(1) DEFAULT NULL,\n  `last_modified_at` datetime DEFAULT NULL,\n  `last_modified_by` int DEFAULT NULL,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `created_by` int DEFAULT NULL,\n  `updated_by` int DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  `deleted_at` datetime DEFAULT NULL,\n  `deleted_by` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `config_key` (`config_key`)\n) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `system_logs`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `system_logs` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `log_level` enum('DEBUG','INFO','WARNING','ERROR','CRITICAL') NOT NULL,\n  `log_category` enum('USER','SYSTEM','DATABASE','API','SECURITY','DICOM','AI','REPORT','NOTIFICATION') NOT NULL,\n  `log_message` text NOT NULL,\n  `log_details` json DEFAULT NULL,\n  `operation` varchar(100) DEFAULT NULL,\n  `resource_type` varchar(50) DEFAULT NULL,\n  `resource_id` varchar(100) DEFAULT NULL,\n  `user_id` int DEFAULT NULL,\n  `username` varchar(100) DEFAULT NULL,\n  `session_id` varchar(100) DEFAULT NULL,\n  `ip_address` varchar(45) DEFAULT NULL,\n  `user_agent` varchar(500) DEFAULT NULL,\n  `request_method` varchar(10) DEFAULT NULL,\n  `request_url` varchar(500) DEFAULT NULL,\n  `request_params` json DEFAULT NULL,\n  `response_status` int DEFAULT NULL,\n  `response_time` float DEFAULT NULL,\n  `exception_type` varchar(200) DEFAULT NULL,\n  `exception_message` text,\n  `stack_trace` text,\n  `created_at` datetime DEFAULT NULL,\n  `log_date` date NOT NULL,\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `system_monitors`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    'CREATE TABLE `system_monitors` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `monitor_time` datetime NOT NULL,\n  `server_name` varchar(100) NOT NULL,\n  `cpu_usage` float DEFAULT NULL,\n  `cpu_load_1m` float DEFAULT NULL,\n  `cpu_load_5m` float DEFAULT NULL,\n  `cpu_load_15m` float DEFAULT NULL,\n  `memory_total` int DEFAULT NULL,\n  `memory_used` int DEFAULT NULL,\n  `memory_free` int DEFAULT NULL,\n  `memory_usage` float DEFAULT NULL,\n  `disk_total` int DEFAULT NULL,\n  `disk_used` int DEFAULT NULL,\n  `disk_free` int DEFAULT NULL,\n  `disk_usage` float DEFAULT NULL,\n  `network_in` int DEFAULT NULL,\n  `network_out` int DEFAULT NULL,\n  `db_connections` int DEFAULT NULL,\n  `db_queries_per_sec` float DEFAULT NULL,\n  `db_slow_queries` int DEFAULT NULL,\n  `active_users` int DEFAULT NULL,\n  `active_sessions` int DEFAULT NULL,\n  `request_count` int DEFAULT NULL,\n  `error_count` int DEFAULT NULL,\n  `studies_processed` int DEFAULT NULL,\n  `reports_generated` int DEFAULT NULL,\n  `ai_tasks_completed` int DEFAULT NULL,\n  `additional_metrics` json DEFAULT NULL,\n  `created_at` datetime DEFAULT NULL,\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `team_invitations`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `team_invitations` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `team_id` int NOT NULL,\n  `inviter_id` int NOT NULL,\n  `invitee_email` varchar(160) NOT NULL,\n  `invitee_user_id` int DEFAULT NULL,\n  `role` enum('LEADER','ADMIN','MEMBER','GUEST') NOT NULL,\n  `status` enum('PENDING','ACCEPTED','EXPIRED','REVOKED') NOT NULL,\n  `token` varchar(120) NOT NULL,\n  `message` text,\n  `created_at` datetime NOT NULL,\n  `expires_at` datetime NOT NULL,\n  `responded_at` datetime DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `token` (`token`),\n  KEY `team_id` (`team_id`),\n  KEY `inviter_id` (`inviter_id`),\n  KEY `invitee_user_id` (`invitee_user_id`),\n  CONSTRAINT `team_invitations_ibfk_1` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`),\n  CONSTRAINT `team_invitations_ibfk_2` FOREIGN KEY (`inviter_id`) REFERENCES `users` (`id`),\n  CONSTRAINT `team_invitations_ibfk_3` FOREIGN KEY (`invitee_user_id`) REFERENCES `users` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `team_join_requests`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `team_join_requests` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `team_id` int NOT NULL,\n  `user_id` int NOT NULL,\n  `message` text,\n  `status` enum('PENDING','APPROVED','REJECTED','CANCELLED') NOT NULL,\n  `created_at` datetime NOT NULL,\n  `reviewed_at` datetime DEFAULT NULL,\n  `reviewer_id` int DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uq_join_request` (`team_id`,`user_id`),\n  KEY `user_id` (`user_id`),\n  KEY `reviewer_id` (`reviewer_id`),\n  CONSTRAINT `team_join_requests_ibfk_1` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`),\n  CONSTRAINT `team_join_requests_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),\n  CONSTRAINT `team_join_requests_ibfk_3` FOREIGN KEY (`reviewer_id`) REFERENCES `users` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `team_memberships`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `team_memberships` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `team_id` int NOT NULL,\n  `user_id` int NOT NULL,\n  `role` enum('LEADER','ADMIN','MEMBER','GUEST') NOT NULL,\n  `status` enum('ACTIVE','INVITED','PENDING','INACTIVE') NOT NULL,\n  `joined_at` datetime NOT NULL,\n  `updated_at` datetime NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uq_team_user` (`team_id`,`user_id`),\n  KEY `user_id` (`user_id`),\n  CONSTRAINT `team_memberships_ibfk_1` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`),\n  CONSTRAINT `team_memberships_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=33 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `teams`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    "CREATE TABLE `teams` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `name` varchar(120) NOT NULL,\n  `description` text,\n  `hospital` varchar(120) DEFAULT NULL,\n  `department` varchar(120) DEFAULT NULL,\n  `creator_id` int DEFAULT NULL COMMENT 'åˆ›å»ºè€…ID',\n  `max_members` int NOT NULL,\n  `is_active` tinyint(1) NOT NULL,\n  `created_at` datetime NOT NULL,\n  `updated_at` datetime NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `name` (`name`),\n  KEY `leader_id` (`creator_id`),\n  CONSTRAINT `teams_ibfk_1` FOREIGN KEY (`creator_id`) REFERENCES `users` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci",
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `user_roles`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    'CREATE TABLE `user_roles` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `user_id` int NOT NULL,\n  `role_id` int NOT NULL,\n  `assigned_at` datetime DEFAULT NULL,\n  `is_active` tinyint(1) DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uk_user_role` (`user_id`,`role_id`),\n  KEY `role_id` (`role_id`),\n  CONSTRAINT `user_roles_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,\n  CONSTRAINT `user_roles_ibfk_2` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
    '/*!40101 SET character_set_client = @saved_cs_client */',
    'DROP TABLE IF EXISTS `users`',
    '/*!40101 SET @saved_cs_client     = @@character_set_client */',
    '/*!50503 SET character_set_client = utf8mb4 */',
    'CREATE TABLE `users` (\n  `id` int NOT NULL AUTO_INCREMENT,\n  `username` varchar(50) NOT NULL,\n  `email` varchar(100) NOT NULL,\n  `phone` varchar(20) DEFAULT NULL,\n  `password_hash` varchar(255) NOT NULL,\n  `salt` varchar(32) NOT NULL,\n  `real_name` varchar(50) NOT NULL,\n  `employee_id` varchar(20) DEFAULT NULL,\n  `department_id` int DEFAULT NULL,\n  `position` varchar(50) DEFAULT NULL,\n  `title` varchar(50) DEFAULT NULL,\n  `status` varchar(20) NOT NULL,\n  `is_verified` tinyint(1) DEFAULT NULL,\n  `is_superuser` tinyint(1) DEFAULT NULL,\n  `is_system_admin` tinyint(1) DEFAULT NULL,\n  `system_admin_level` int DEFAULT NULL,\n  `created_at` datetime DEFAULT NULL,\n  `updated_at` datetime DEFAULT NULL,\n  `is_deleted` tinyint(1) DEFAULT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `username` (`username`),\n  UNIQUE KEY `email` (`email`),\n  UNIQUE KEY `phone` (`phone`),\n  UNIQUE KEY `employee_id` (`employee_id`),\n  KEY `department_id` (`department_id`),\n  CONSTRAINT `users_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`)\n) ENGINE=InnoDB AUTO_INCREMENT=38 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci',
    '/*!40101 SET character_set_client = @saved_cs_client */',
    '/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */',
    '/*!40101 SET SQL_MODE=@OLD_SQL_MODE */',
    '/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */',
    '/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */',
    '/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */',
    '/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */',
    '/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */',
    '/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */',
]

TABLES = [
    'ai_tasks',
    'departments',
    'diagnostic_reports',
    'image_annotations',
    'image_files',
    'instances',
    'notifications',
    'patient_allergies',
    'patient_medical_history',
    'patient_visits',
    'patients',
    'permissions',
    'report_findings',
    'report_revisions',
    'report_templates',
    'role_permissions',
    'roles',
    'series',
    'studies',
    'system_alerts',
    'system_configs',
    'system_logs',
    'system_monitors',
    'team_invitations',
    'team_join_requests',
    'team_memberships',
    'teams',
    'user_roles',
    'users',
]


def upgrade() -> None:
    bind = op.get_bind()
    for statement in SCHEMA_STATEMENTS:
        bind.exec_driver_sql(statement)


def downgrade() -> None:
    bind = op.get_bind()
    bind.exec_driver_sql("SET FOREIGN_KEY_CHECKS=0")
    try:
        for table_name in reversed(TABLES):
            bind.exec_driver_sql(f"DROP TABLE IF EXISTS `{table_name}`")
    finally:
        bind.exec_driver_sql("SET FOREIGN_KEY_CHECKS=1")
