"""server schema baseline

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-05-08 00:00:00
"""

from __future__ import annotations

from alembic import op

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


CREATE_TABLE_STATEMENTS = (
    """\
CREATE TABLE IF NOT EXISTS `departments` (
  `id` int NOT NULL AUTO_INCREMENT,
  `code` varchar(50) NOT NULL,
  `name` varchar(100) NOT NULL,
  `full_name` varchar(200) DEFAULT NULL,
  `description` text,
  `parent_id` int DEFAULT NULL,
  `level` int DEFAULT NULL,
  `path` varchar(500) DEFAULT NULL,
  `sort_order` int DEFAULT NULL,
  `status` varchar(20) NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  KEY `parent_id` (`parent_id`),
  CONSTRAINT `departments_ibfk_1` FOREIGN KEY (`parent_id`) REFERENCES `departments` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `notifications` (
  `id` int NOT NULL AUTO_INCREMENT,
  `notification_type` enum('INFO','WARNING','ERROR','SUCCESS','SYSTEM','REMINDER') NOT NULL,
  `title` varchar(200) NOT NULL,
  `content` text NOT NULL,
  `status` enum('PENDING','SENT','READ','FAILED','EXPIRED') DEFAULT NULL,
  `recipient_id` int DEFAULT NULL,
  `recipient_type` varchar(50) DEFAULT NULL,
  `recipient_email` varchar(200) DEFAULT NULL,
  `recipient_phone` varchar(20) DEFAULT NULL,
  `sender_id` int DEFAULT NULL,
  `sender_name` varchar(100) DEFAULT NULL,
  `channels` json DEFAULT NULL,
  `related_type` varchar(50) DEFAULT NULL,
  `related_id` varchar(100) DEFAULT NULL,
  `related_data` json DEFAULT NULL,
  `scheduled_at` datetime DEFAULT NULL,
  `sent_at` datetime DEFAULT NULL,
  `read_at` datetime DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `retry_count` int DEFAULT NULL,
  `max_retries` int DEFAULT NULL,
  `last_error` text,
  `priority` int DEFAULT NULL,
  `tags` json DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `patients` (
  `id` int NOT NULL AUTO_INCREMENT,
  `patient_id` varchar(50) NOT NULL,
  `hospital_id` varchar(50) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `name_en` varchar(200) DEFAULT NULL,
  `gender` enum('MALE','FEMALE','OTHER','UNKNOWN') NOT NULL,
  `birth_date` date DEFAULT NULL,
  `age` int DEFAULT NULL,
  `id_card` varchar(18) DEFAULT NULL,
  `passport` varchar(50) DEFAULT NULL,
  `nationality` varchar(50) DEFAULT NULL,
  `ethnicity` varchar(50) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `phone_backup` varchar(20) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `address` varchar(500) DEFAULT NULL,
  `postal_code` varchar(10) DEFAULT NULL,
  `emergency_contact_name` varchar(100) DEFAULT NULL,
  `emergency_contact_phone` varchar(20) DEFAULT NULL,
  `emergency_contact_relation` varchar(50) DEFAULT NULL,
  `blood_type` enum('A','B','AB','O','UNKNOWN') DEFAULT NULL,
  `rh_factor` enum('POSITIVE','NEGATIVE','UNKNOWN') DEFAULT NULL,
  `height` decimal(5,2) DEFAULT NULL,
  `weight` decimal(5,2) DEFAULT NULL,
  `bmi` decimal(5,2) DEFAULT NULL,
  `marital_status` enum('SINGLE','MARRIED','DIVORCED','WIDOWED','UNKNOWN') DEFAULT NULL,
  `occupation` varchar(100) DEFAULT NULL,
  `education` varchar(50) DEFAULT NULL,
  `insurance_type` varchar(50) DEFAULT NULL,
  `insurance_number` varchar(50) DEFAULT NULL,
  `status` enum('ACTIVE','INACTIVE','DECEASED','MERGED') NOT NULL,
  `is_vip` tinyint(1) DEFAULT NULL,
  `is_high_risk` tinyint(1) DEFAULT NULL,
  `notes` text,
  `tags` json DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `patient_id` (`patient_id`),
  UNIQUE KEY `hospital_id` (`hospital_id`),
  UNIQUE KEY `id_card` (`id_card`),
  UNIQUE KEY `passport` (`passport`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `permissions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `code` varchar(100) NOT NULL,
  `name` varchar(50) NOT NULL,
  `description` text,
  `module` varchar(50) NOT NULL,
  `resource` varchar(50) NOT NULL,
  `action` varchar(50) NOT NULL,
  `status` varchar(20) NOT NULL,
  `is_system` tinyint(1) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `report_templates` (
  `id` int NOT NULL AUTO_INCREMENT,
  `template_name` varchar(100) NOT NULL,
  `template_code` varchar(50) NOT NULL,
  `template_type` enum('STRUCTURED','FREE_TEXT','HYBRID','CHECKLIST') NOT NULL,
  `report_type` enum('RADIOLOGY','PATHOLOGY','LABORATORY','ULTRASOUND','ENDOSCOPY','ECG','OTHER') NOT NULL,
  `modality` varchar(20) DEFAULT NULL,
  `body_part` varchar(50) DEFAULT NULL,
  `template_content` json NOT NULL,
  `default_values` json DEFAULT NULL,
  `validation_rules` json DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT NULL,
  `is_default` tinyint(1) DEFAULT NULL,
  `version` varchar(20) DEFAULT NULL,
  `description` text,
  `usage_count` int DEFAULT NULL,
  `last_used_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `template_code` (`template_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `roles` (
  `id` int NOT NULL AUTO_INCREMENT,
  `code` varchar(50) NOT NULL,
  `name` varchar(50) NOT NULL,
  `description` text,
  `level` int DEFAULT NULL,
  `status` varchar(20) NOT NULL,
  `is_system` tinyint(1) DEFAULT NULL,
  `is_default` tinyint(1) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `studies` (
  `id` int NOT NULL AUTO_INCREMENT,
  `study_instance_uid` varchar(64) NOT NULL,
  `study_id` varchar(16) DEFAULT NULL,
  `accession_number` varchar(16) DEFAULT NULL,
  `patient_id` int NOT NULL,
  `study_date` date DEFAULT NULL,
  `study_time` varchar(16) DEFAULT NULL,
  `study_description` varchar(64) DEFAULT NULL,
  `modality` enum('CT','MR','XR','US','NM','PT','MG','DX','CR','DR','RF','SC','OTHER') DEFAULT NULL,
  `body_part` enum('HEAD','NECK','CHEST','ABDOMEN','PELVIS','SPINE','EXTREMITY','WHOLE_BODY','OTHER') DEFAULT NULL,
  `referring_physician` varchar(64) DEFAULT NULL,
  `performing_physician` varchar(64) DEFAULT NULL,
  `reading_physician` varchar(64) DEFAULT NULL,
  `institution_name` varchar(64) DEFAULT NULL,
  `station_name` varchar(16) DEFAULT NULL,
  `manufacturer` varchar(64) DEFAULT NULL,
  `model_name` varchar(64) DEFAULT NULL,
  `series_count` int DEFAULT NULL,
  `instance_count` int DEFAULT NULL,
  `total_size` int DEFAULT NULL,
  `status` enum('SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED','ARCHIVED') NOT NULL,
  `priority` varchar(20) DEFAULT NULL,
  `quality` enum('EXCELLENT','GOOD','ACCEPTABLE','POOR','UNACCEPTABLE') DEFAULT NULL,
  `notes` text,
  `tags` json DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `study_instance_uid` (`study_instance_uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `system_alerts` (
  `id` int NOT NULL AUTO_INCREMENT,
  `alert_type` varchar(50) NOT NULL,
  `alert_level` enum('DEBUG','INFO','WARNING','ERROR','CRITICAL') NOT NULL,
  `alert_title` varchar(200) NOT NULL,
  `alert_message` text NOT NULL,
  `source_type` varchar(50) DEFAULT NULL,
  `source_id` varchar(100) DEFAULT NULL,
  `server_name` varchar(100) DEFAULT NULL,
  `is_resolved` tinyint(1) DEFAULT NULL,
  `resolved_at` datetime DEFAULT NULL,
  `resolved_by` int DEFAULT NULL,
  `resolution_notes` text,
  `alert_data` json DEFAULT NULL,
  `threshold_value` float DEFAULT NULL,
  `current_value` float DEFAULT NULL,
  `notification_sent` tinyint(1) DEFAULT NULL,
  `notification_count` int DEFAULT NULL,
  `last_notification_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `system_configs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `config_key` varchar(100) NOT NULL,
  `config_name` varchar(200) NOT NULL,
  `config_type` enum('SYSTEM','DATABASE','SECURITY','NOTIFICATION','AI','DICOM','STORAGE','NETWORK','UI','WORKFLOW') NOT NULL,
  `data_type` enum('STRING','INTEGER','FLOAT','BOOLEAN','JSON','ARRAY','DATE','DATETIME') NOT NULL,
  `config_value` text,
  `default_value` text,
  `description` text,
  `is_required` tinyint(1) DEFAULT NULL,
  `is_encrypted` tinyint(1) DEFAULT NULL,
  `is_readonly` tinyint(1) DEFAULT NULL,
  `is_system` tinyint(1) DEFAULT NULL,
  `validation_rules` json DEFAULT NULL,
  `allowed_values` json DEFAULT NULL,
  `min_value` float DEFAULT NULL,
  `max_value` float DEFAULT NULL,
  `config_group` varchar(100) DEFAULT NULL,
  `sort_order` int DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT NULL,
  `last_modified_at` datetime DEFAULT NULL,
  `last_modified_by` int DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `config_key` (`config_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `system_logs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `log_level` enum('DEBUG','INFO','WARNING','ERROR','CRITICAL') NOT NULL,
  `log_category` enum('USER','SYSTEM','DATABASE','API','SECURITY','DICOM','AI','REPORT','NOTIFICATION') NOT NULL,
  `log_message` text NOT NULL,
  `log_details` json DEFAULT NULL,
  `operation` varchar(100) DEFAULT NULL,
  `resource_type` varchar(50) DEFAULT NULL,
  `resource_id` varchar(100) DEFAULT NULL,
  `user_id` int DEFAULT NULL,
  `username` varchar(100) DEFAULT NULL,
  `session_id` varchar(100) DEFAULT NULL,
  `ip_address` varchar(45) DEFAULT NULL,
  `user_agent` varchar(500) DEFAULT NULL,
  `request_method` varchar(10) DEFAULT NULL,
  `request_url` varchar(500) DEFAULT NULL,
  `request_params` json DEFAULT NULL,
  `response_status` int DEFAULT NULL,
  `response_time` float DEFAULT NULL,
  `exception_type` varchar(200) DEFAULT NULL,
  `exception_message` text,
  `stack_trace` text,
  `created_at` datetime DEFAULT NULL,
  `log_date` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `system_monitors` (
  `id` int NOT NULL AUTO_INCREMENT,
  `monitor_time` datetime NOT NULL,
  `server_name` varchar(100) NOT NULL,
  `cpu_usage` float DEFAULT NULL,
  `cpu_load_1m` float DEFAULT NULL,
  `cpu_load_5m` float DEFAULT NULL,
  `cpu_load_15m` float DEFAULT NULL,
  `memory_total` int DEFAULT NULL,
  `memory_used` int DEFAULT NULL,
  `memory_free` int DEFAULT NULL,
  `memory_usage` float DEFAULT NULL,
  `disk_total` int DEFAULT NULL,
  `disk_used` int DEFAULT NULL,
  `disk_free` int DEFAULT NULL,
  `disk_usage` float DEFAULT NULL,
  `network_in` int DEFAULT NULL,
  `network_out` int DEFAULT NULL,
  `db_connections` int DEFAULT NULL,
  `db_queries_per_sec` float DEFAULT NULL,
  `db_slow_queries` int DEFAULT NULL,
  `active_users` int DEFAULT NULL,
  `active_sessions` int DEFAULT NULL,
  `request_count` int DEFAULT NULL,
  `error_count` int DEFAULT NULL,
  `studies_processed` int DEFAULT NULL,
  `reports_generated` int DEFAULT NULL,
  `ai_tasks_completed` int DEFAULT NULL,
  `additional_metrics` json DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `series` (
  `id` int NOT NULL AUTO_INCREMENT,
  `series_instance_uid` varchar(64) NOT NULL,
  `series_number` int DEFAULT NULL,
  `study_id` int NOT NULL,
  `series_date` date DEFAULT NULL,
  `series_time` varchar(16) DEFAULT NULL,
  `series_description` varchar(64) DEFAULT NULL,
  `protocol_name` varchar(64) DEFAULT NULL,
  `modality` enum('CT','MR','XR','US','NM','PT','MG','DX','CR','DR','RF','SC','OTHER') DEFAULT NULL,
  `body_part` enum('HEAD','NECK','CHEST','ABDOMEN','PELVIS','SPINE','EXTREMITY','WHOLE_BODY','OTHER') DEFAULT NULL,
  `slice_thickness` float DEFAULT NULL,
  `pixel_spacing` varchar(32) DEFAULT NULL,
  `image_orientation` varchar(64) DEFAULT NULL,
  `kvp` float DEFAULT NULL,
  `exposure_time` float DEFAULT NULL,
  `tube_current` float DEFAULT NULL,
  `instance_count` int DEFAULT NULL,
  `total_size` int DEFAULT NULL,
  `status` enum('RECEIVING','RECEIVED','PROCESSING','PROCESSED','FAILED') NOT NULL,
  `quality` enum('EXCELLENT','GOOD','ACCEPTABLE','POOR','UNACCEPTABLE') DEFAULT NULL,
  `notes` text,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `series_instance_uid` (`series_instance_uid`),
  KEY `study_id` (`study_id`),
  CONSTRAINT `series_ibfk_1` FOREIGN KEY (`study_id`) REFERENCES `studies` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `instances` (
  `id` int NOT NULL AUTO_INCREMENT,
  `sop_instance_uid` varchar(64) NOT NULL,
  `sop_class_uid` varchar(64) DEFAULT NULL,
  `instance_number` int DEFAULT NULL,
  `series_id` int NOT NULL,
  `file_path` varchar(500) DEFAULT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `file_size` int DEFAULT NULL,
  `file_hash` varchar(64) DEFAULT NULL,
  `image_type` varchar(64) DEFAULT NULL,
  `rows` int DEFAULT NULL,
  `columns` int DEFAULT NULL,
  `bits_allocated` int DEFAULT NULL,
  `bits_stored` int DEFAULT NULL,
  `slice_location` float DEFAULT NULL,
  `image_position` varchar(64) DEFAULT NULL,
  `window_center` float DEFAULT NULL,
  `window_width` float DEFAULT NULL,
  `status` enum('UPLOADING','UPLOADED','PROCESSING','PROCESSED','FAILED','ARCHIVED') NOT NULL,
  `quality` enum('EXCELLENT','GOOD','ACCEPTABLE','POOR','UNACCEPTABLE') DEFAULT NULL,
  `thumbnail_path` varchar(500) DEFAULT NULL,
  `preview_path` varchar(500) DEFAULT NULL,
  `processed_at` datetime DEFAULT NULL,
  `notes` text,
  `dicom_metadata` json DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `sop_instance_uid` (`sop_instance_uid`),
  KEY `series_id` (`series_id`),
  CONSTRAINT `instances_ibfk_1` FOREIGN KEY (`series_id`) REFERENCES `series` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `password_hash` varchar(255) NOT NULL,
  `salt` varchar(32) NOT NULL,
  `real_name` varchar(50) NOT NULL,
  `employee_id` varchar(20) DEFAULT NULL,
  `department_id` int DEFAULT NULL,
  `position` varchar(50) DEFAULT NULL,
  `title` varchar(50) DEFAULT NULL,
  `status` varchar(20) NOT NULL,
  `is_verified` tinyint(1) DEFAULT NULL,
  `is_superuser` tinyint(1) DEFAULT NULL,
  `is_system_admin` tinyint(1) DEFAULT NULL,
  `system_admin_level` int DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `phone` (`phone`),
  UNIQUE KEY `employee_id` (`employee_id`),
  KEY `department_id` (`department_id`),
  CONSTRAINT `users_ibfk_1` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `diagnostic_reports` (
  `id` int NOT NULL AUTO_INCREMENT,
  `report_number` varchar(50) NOT NULL,
  `study_id` int NOT NULL,
  `patient_id` int NOT NULL,
  `template_id` int DEFAULT NULL,
  `report_type` enum('RADIOLOGY','PATHOLOGY','LABORATORY','ULTRASOUND','ENDOSCOPY','ECG','OTHER') NOT NULL,
  `report_title` varchar(200) NOT NULL,
  `status` enum('DRAFT','IN_REVIEW','APPROVED','FINALIZED','CANCELLED','ARCHIVED') NOT NULL,
  `priority` enum('LOW','NORMAL','HIGH','URGENT','STAT') DEFAULT NULL,
  `clinical_history` text,
  `examination_technique` text,
  `findings` text NOT NULL,
  `impression` text NOT NULL,
  `recommendations` text,
  `structured_data` json DEFAULT NULL,
  `measurements` json DEFAULT NULL,
  `annotations` json DEFAULT NULL,
  `primary_diagnosis` varchar(200) DEFAULT NULL,
  `secondary_diagnosis` text,
  `diagnosis_codes` json DEFAULT NULL,
  `diagnosis_level` enum('NORMAL','ABNORMAL','SUSPICIOUS','MALIGNANT','BENIGN','INDETERMINATE') DEFAULT NULL,
  `confidence_score` float DEFAULT NULL,
  `examination_date` date DEFAULT NULL,
  `report_date` date NOT NULL,
  `reviewed_date` date DEFAULT NULL,
  `finalized_date` date DEFAULT NULL,
  `reporting_physician` varchar(100) NOT NULL,
  `reviewing_physician` varchar(100) DEFAULT NULL,
  `attending_physician` varchar(100) DEFAULT NULL,
  `ai_assisted` tinyint(1) DEFAULT NULL,
  `ai_suggestions` json DEFAULT NULL,
  `ai_confidence` float DEFAULT NULL,
  `quality_score` float DEFAULT NULL,
  `quality_notes` text,
  `urgency_flag` tinyint(1) DEFAULT NULL,
  `critical_flag` tinyint(1) DEFAULT NULL,
  `follow_up_required` tinyint(1) DEFAULT NULL,
  `follow_up_date` date DEFAULT NULL,
  `notes` text,
  `tags` json DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `report_number` (`report_number`),
  KEY `template_id` (`template_id`),
  CONSTRAINT `diagnostic_reports_ibfk_1` FOREIGN KEY (`template_id`) REFERENCES `report_templates` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `image_files` (
  `id` int NOT NULL AUTO_INCREMENT,
  `file_uuid` varchar(36) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'æ–‡ä»¶å”¯ä¸€æ ‡è¯†',
  `original_filename` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'åŽŸå§‹æ–‡ä»¶å',
  `file_type` enum('DICOM','JPEG','PNG','TIFF','OTHER') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'OTHER',
  `mime_type` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'MIMEç±»åž‹',
  `file_size` bigint NOT NULL DEFAULT '0' COMMENT 'æ–‡ä»¶å¤§å°(å­—èŠ‚)',
  `file_hash` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'æ–‡ä»¶MD5å“ˆå¸Œå€¼',
  `storage_path` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'å­˜å‚¨è·¯å¾„',
  `thumbnail_path` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'ç¼©ç•¥å›¾è·¯å¾„',
  `uploaded_by` int NOT NULL COMMENT 'ä¸Šä¼ ç”¨æˆ·ID',
  `patient_id` int DEFAULT NULL COMMENT 'å…³è”æ‚£è€…ID',
  `study_id` int DEFAULT NULL COMMENT 'å…³è”æ£€æŸ¥ID',
  `series_id` int DEFAULT NULL COMMENT 'å…³è”åºåˆ—ID',
  `modality` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'å½±åƒæ¨¡æ€(CT/MRI/X-Rayç­‰)',
  `body_part` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'æ£€æŸ¥éƒ¨ä½',
  `study_date` datetime DEFAULT NULL COMMENT 'æ£€æŸ¥æ—¥æœŸ',
  `description` text COLLATE utf8mb4_unicode_ci COMMENT 'æ–‡ä»¶æè¿°',
  `annotation` text COLLATE utf8mb4_unicode_ci COMMENT '标注数据(JSON格式)',
  `status` enum('UPLOADING','UPLOADED','PROCESSING','PROCESSED','FAILED','ARCHIVED','DELETED') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'UPLOADING',
  `upload_progress` int NOT NULL DEFAULT '0' COMMENT 'ä¸Šä¼ è¿›åº¦(0-100)',
  `is_chunked` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'æ˜¯å¦åˆ†ç‰‡ä¸Šä¼ ',
  `total_chunks` int DEFAULT NULL COMMENT 'æ€»åˆ†ç‰‡æ•°',
  `uploaded_chunks` text COLLATE utf8mb4_unicode_ci COMMENT 'å·²ä¸Šä¼ åˆ†ç‰‡åˆ—è¡¨(JSON)',
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'æ˜¯å¦å·²åˆ é™¤',
  `deleted_at` datetime DEFAULT NULL COMMENT 'åˆ é™¤æ—¶é—´',
  `deleted_by` int DEFAULT NULL COMMENT 'åˆ é™¤ç”¨æˆ·ID',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'åˆ›å»ºæ—¶é—´',
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'æ›´æ–°æ—¶é—´',
  `uploaded_at` datetime DEFAULT NULL COMMENT 'ä¸Šä¼ å®Œæˆæ—¶é—´',
  PRIMARY KEY (`id`),
  UNIQUE KEY `file_uuid` (`file_uuid`),
  KEY `idx_file_uuid` (`file_uuid`),
  KEY `idx_uploaded_by` (`uploaded_by`),
  KEY `idx_patient_id` (`patient_id`),
  KEY `idx_study_id` (`study_id`),
  KEY `idx_modality` (`modality`),
  KEY `idx_created_at` (`created_at`),
  KEY `idx_status` (`status`),
  KEY `idx_is_deleted` (`is_deleted`),
  KEY `idx_series_id` (`series_id`),
  CONSTRAINT `image_files_ibfk_1` FOREIGN KEY (`uploaded_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT,
  CONSTRAINT `image_files_ibfk_2` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`) ON DELETE SET NULL,
  CONSTRAINT `image_files_ibfk_3` FOREIGN KEY (`series_id`) REFERENCES `series` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='å½±åƒæ–‡ä»¶è¡¨';
    """,

    """\
CREATE TABLE IF NOT EXISTS `patient_allergies` (
  `id` int NOT NULL AUTO_INCREMENT,
  `patient_id` int NOT NULL,
  `allergen` varchar(200) NOT NULL,
  `allergen_type` varchar(50) DEFAULT NULL,
  `reaction` text,
  `severity` enum('MILD','MODERATE','SEVERE','CRITICAL','UNKNOWN') DEFAULT NULL,
  `onset_date` date DEFAULT NULL,
  `last_reaction_date` date DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT NULL,
  `verified` tinyint(1) DEFAULT NULL,
  `notes` text,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `patient_id` (`patient_id`),
  CONSTRAINT `patient_allergies_ibfk_1` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `patient_medical_history` (
  `id` int NOT NULL AUTO_INCREMENT,
  `patient_id` int NOT NULL,
  `condition` varchar(200) NOT NULL,
  `condition_code` varchar(20) DEFAULT NULL,
  `category` varchar(50) DEFAULT NULL,
  `onset_date` date DEFAULT NULL,
  `resolution_date` date DEFAULT NULL,
  `description` text,
  `treatment` text,
  `outcome` varchar(100) DEFAULT NULL,
  `is_chronic` tinyint(1) DEFAULT NULL,
  `is_hereditary` tinyint(1) DEFAULT NULL,
  `severity` enum('MILD','MODERATE','SEVERE','CRITICAL','UNKNOWN') DEFAULT NULL,
  `related_family_member` varchar(50) DEFAULT NULL,
  `notes` text,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `patient_id` (`patient_id`),
  CONSTRAINT `patient_medical_history_ibfk_1` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `patient_visits` (
  `id` int NOT NULL AUTO_INCREMENT,
  `visit_number` varchar(50) NOT NULL,
  `patient_id` int NOT NULL,
  `visit_type` enum('OUTPATIENT','INPATIENT','EMERGENCY','PHYSICAL_EXAM','FOLLOW_UP') NOT NULL,
  `visit_date` datetime NOT NULL,
  `department_id` int DEFAULT NULL,
  `doctor_id` int DEFAULT NULL,
  `status` enum('SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED','NO_SHOW') NOT NULL,
  `priority` varchar(20) DEFAULT NULL,
  `chief_complaint` text,
  `present_illness` text,
  `diagnosis_preliminary` text,
  `diagnosis_final` text,
  `treatment_plan` text,
  `temperature` decimal(4,1) DEFAULT NULL,
  `blood_pressure_systolic` int DEFAULT NULL,
  `blood_pressure_diastolic` int DEFAULT NULL,
  `heart_rate` int DEFAULT NULL,
  `respiratory_rate` int DEFAULT NULL,
  `oxygen_saturation` decimal(5,2) DEFAULT NULL,
  `total_cost` decimal(10,2) DEFAULT NULL,
  `insurance_coverage` decimal(10,2) DEFAULT NULL,
  `self_payment` decimal(10,2) DEFAULT NULL,
  `notes` text,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `visit_number` (`visit_number`),
  KEY `patient_id` (`patient_id`),
  CONSTRAINT `patient_visits_ibfk_1` FOREIGN KEY (`patient_id`) REFERENCES `patients` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `report_findings` (
  `id` int NOT NULL AUTO_INCREMENT,
  `report_id` int NOT NULL,
  `finding_category` varchar(100) NOT NULL,
  `finding_description` text NOT NULL,
  `location` varchar(100) DEFAULT NULL,
  `severity` varchar(50) DEFAULT NULL,
  `measurements` json DEFAULT NULL,
  `coordinates` json DEFAULT NULL,
  `significance` varchar(100) DEFAULT NULL,
  `differential_diagnosis` text,
  `sort_order` int DEFAULT NULL,
  `is_key_finding` tinyint(1) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `report_id` (`report_id`),
  CONSTRAINT `report_findings_ibfk_1` FOREIGN KEY (`report_id`) REFERENCES `diagnostic_reports` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `report_revisions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `report_id` int NOT NULL,
  `revision_number` int NOT NULL,
  `revision_reason` varchar(200) NOT NULL,
  `revision_description` text,
  `previous_content` json NOT NULL,
  `current_content` json NOT NULL,
  `changed_fields` json DEFAULT NULL,
  `revised_by` int NOT NULL,
  `revised_at` datetime DEFAULT NULL,
  `approved_by` int DEFAULT NULL,
  `approved_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `report_id` (`report_id`),
  CONSTRAINT `report_revisions_ibfk_1` FOREIGN KEY (`report_id`) REFERENCES `diagnostic_reports` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `role_permissions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `role_id` int NOT NULL,
  `permission_id` int NOT NULL,
  `granted_at` datetime DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_role_permission` (`role_id`,`permission_id`),
  KEY `permission_id` (`permission_id`),
  CONSTRAINT `role_permissions_ibfk_1` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `role_permissions_ibfk_2` FOREIGN KEY (`permission_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `teams` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(120) NOT NULL,
  `description` text,
  `hospital` varchar(120) DEFAULT NULL,
  `department` varchar(120) DEFAULT NULL,
  `creator_id` int DEFAULT NULL COMMENT 'åˆ›å»ºè€…ID',
  `max_members` int NOT NULL,
  `is_active` tinyint(1) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `leader_id` (`creator_id`),
  CONSTRAINT `teams_ibfk_1` FOREIGN KEY (`creator_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `user_roles` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `role_id` int NOT NULL,
  `assigned_at` datetime DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_role` (`user_id`,`role_id`),
  KEY `role_id` (`role_id`),
  CONSTRAINT `user_roles_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `user_roles_ibfk_2` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `image_annotations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `image_file_id` int NOT NULL COMMENT 'å½±åƒæ–‡ä»¶ID',
  `annotation_type` enum('POINT','LINE','RECTANGLE','CIRCLE','POLYGON','FREEHAND','TEXT','MEASUREMENT') NOT NULL,
  `coordinates` json NOT NULL,
  `label` varchar(100) DEFAULT NULL,
  `description` text,
  `measurement_value` float DEFAULT NULL,
  `measurement_unit` varchar(20) DEFAULT NULL,
  `color` varchar(7) DEFAULT NULL,
  `thickness` int DEFAULT NULL,
  `opacity` float DEFAULT NULL,
  `is_visible` tinyint(1) DEFAULT NULL,
  `is_locked` tinyint(1) DEFAULT NULL,
  `notes` text,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_image_file_id` (`image_file_id`),
  CONSTRAINT `fk_image_annotations_image_file` FOREIGN KEY (`image_file_id`) REFERENCES `image_files` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `ai_tasks` (
  `id` int NOT NULL AUTO_INCREMENT,
  `task_id` varchar(64) NOT NULL,
  `study_id` int NOT NULL,
  `task_name` varchar(100) NOT NULL,
  `task_type` varchar(50) NOT NULL,
  `model_name` varchar(100) NOT NULL,
  `model_version` varchar(20) DEFAULT NULL,
  `input_parameters` json DEFAULT NULL,
  `status` enum('PENDING','RUNNING','COMPLETED','FAILED','CANCELLED') NOT NULL,
  `progress` float DEFAULT NULL,
  `started_at` datetime DEFAULT NULL,
  `completed_at` datetime DEFAULT NULL,
  `duration` float DEFAULT NULL,
  `result` json DEFAULT NULL,
  `confidence` float DEFAULT NULL,
  `error_message` text,
  `notes` text,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_by` int DEFAULT NULL,
  `updated_by` int DEFAULT NULL,
  `is_deleted` tinyint(1) DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `deleted_by` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `task_id` (`task_id`),
  KEY `study_id` (`study_id`),
  CONSTRAINT `ai_tasks_ibfk_1` FOREIGN KEY (`study_id`) REFERENCES `studies` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `team_invitations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `team_id` int NOT NULL,
  `inviter_id` int NOT NULL,
  `invitee_email` varchar(160) NOT NULL,
  `invitee_user_id` int DEFAULT NULL,
  `role` enum('LEADER','ADMIN','MEMBER','GUEST') NOT NULL,
  `status` enum('PENDING','ACCEPTED','EXPIRED','REVOKED') NOT NULL,
  `token` varchar(120) NOT NULL,
  `message` text,
  `created_at` datetime NOT NULL,
  `expires_at` datetime NOT NULL,
  `responded_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `token` (`token`),
  KEY `team_id` (`team_id`),
  KEY `inviter_id` (`inviter_id`),
  KEY `invitee_user_id` (`invitee_user_id`),
  CONSTRAINT `team_invitations_ibfk_1` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`),
  CONSTRAINT `team_invitations_ibfk_2` FOREIGN KEY (`inviter_id`) REFERENCES `users` (`id`),
  CONSTRAINT `team_invitations_ibfk_3` FOREIGN KEY (`invitee_user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `team_join_requests` (
  `id` int NOT NULL AUTO_INCREMENT,
  `team_id` int NOT NULL,
  `user_id` int NOT NULL,
  `message` text,
  `status` enum('PENDING','APPROVED','REJECTED','CANCELLED') NOT NULL,
  `created_at` datetime NOT NULL,
  `reviewed_at` datetime DEFAULT NULL,
  `reviewer_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_join_request` (`team_id`,`user_id`),
  KEY `user_id` (`user_id`),
  KEY `reviewer_id` (`reviewer_id`),
  CONSTRAINT `team_join_requests_ibfk_1` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`),
  CONSTRAINT `team_join_requests_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `team_join_requests_ibfk_3` FOREIGN KEY (`reviewer_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,

    """\
CREATE TABLE IF NOT EXISTS `team_memberships` (
  `id` int NOT NULL AUTO_INCREMENT,
  `team_id` int NOT NULL,
  `user_id` int NOT NULL,
  `role` enum('LEADER','ADMIN','MEMBER','GUEST') NOT NULL,
  `status` enum('ACTIVE','INVITED','PENDING','INACTIVE') NOT NULL,
  `joined_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_team_user` (`team_id`,`user_id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `team_memberships_ibfk_1` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`),
  CONSTRAINT `team_memberships_ibfk_2` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    """,
)

def upgrade() -> None:
    for statement in CREATE_TABLE_STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    raise NotImplementedError(
        "0001_initial_schema is a production baseline; downgrade would require "
        "dropping all application tables. Restore from a database backup instead."
    )
